# Generated by Django 6.0.2 on 2026-04-13 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_fee', models.DecimalField(decimal_places=2, default=1000, max_digits=10)),
                ('express_fee', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif livraison Ouagadougou',
                'verbose_name_plural': 'Tarifs livraison',
            },
        ),
        migrations.AlterModelOptions(
            name='ticketstatushistory',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='deliveryticket',
            old_name='claimed_at',
            new_name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='deliveryticket',
            name='delivery_city',
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='delivery_quartier',
            field=models.CharField(default='', max_length=100, verbose_name='Quartier acheteur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard (2-6h)'), ('express', 'Express (-2h)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='pickup_address',
            field=models.TextField(default='', verbose_name='Adresse de collecte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryticket',
            name='pickup_quartier',
            field=models.CharField(default='', max_length=100, verbose_name='Quartier vendeur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_delivery': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='delivery_address',
            field=models.TextField(verbose_name='Adresse de livraison'),
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryticket',
            name='status',
            field=models.CharField(choices=[('pending', "En attente d'un livreur"), ('assigned', 'Livreur assigné'), ('picked_up', 'Colis récupéré chez le vendeur'), ('en_route', "En route vers l'acheteur"), ('delivered', 'Livré'), ('failed', 'Échec de livraison')], db_index=True, default='pending', max_length=20),
        ),
    ]
