# Generated by Django 6.0.2 on 2026-04-13 22:11

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cloudinary_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='Est livreur'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('moto', 'Moto'), ('velo', 'Vélo'), ('voiture', 'Voiture'), ('autre', 'Autre')], default='moto', max_length=20)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('active', 'Actif'), ('inactive', 'Inactif'), ('banned', 'Suspendu')], default='pending', max_length=20)),
                ('id_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livreur',
                'verbose_name_plural': 'Livreurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
